import 'reflect-metadata';
import { NonEmptyArray } from 'type-graphql';
import {
  FindManyUserResolver
} from '@generated/type-graphql';
import Container from 'typedi';
export const autogeneratedResolver = (): NonEmptyArray<Function> => {
  Container.set({ id: FindManyUserResolver, type: FindManyUserResolver });
  return [
    FindManyUserResolver,
  ];
 
  
};
