import 'reflect-metadata';
import { NonEmptyArray } from 'type-graphql';
import {
  FindManyUserResolver,
  FindManyStudentResolver,
  FindFirstTeacherResolver,
} from '@generated/type-graphql';
import Container from 'typedi';
export const autogeneratedResolver = (): NonEmptyArray<Function> => {
  Container.set({ id: FindManyUserResolver, type: FindManyUserResolver });
  Container.set({ id: FindManyStudentResolver, type: FindManyStudentResolver });
  Container.set({
    id: FindFirstTeacherResolver,
    type: FindFirstTeacherResolver,
  });
  return [
    FindManyUserResolver,
    FindFirstTeacherResolver,
    FindManyStudentResolver,
  ];
};
